Update cleanup.yml

diff --git a/.github/workflows/cleanup.yml b/.github/workflows/cleanup.yml
--- a/.github/workflows/cleanup.yml
+++ b/.github/workflows/cleanup.yml
@@ -1,30 +1,30 @@
-name: Cleanup Output Directory
+# name: Cleanup Output Directory
 
-on:
-  schedule:
-    - cron: '0 0 * * *'  # Runs every 24 hours
-  workflow_dispatch:  
+# on:
+#   schedule:
+#     - cron: '0 0 * * *'  
+#   workflow_dispatch:  
 
-jobs:
-  cleanup:
-    runs-on: ubuntu-latest
+# jobs:
+#   cleanup:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          persist-credentials: false  # Disable default GitHub token
+#     steps:
+#       - name: Checkout Repository
+#         uses: actions/checkout@v4
+#         with:
+#           persist-credentials: false  
 
-      - name: Remove Output Directory Contents
-        run: |
-          rm -rf output/*  # Deletes all files inside output directory
+#       - name: Remove Output Directory Contents
+#         run: |
+#           rm -rf output/*  # Deletes all files inside output directory
 
-      - name: Commit and Push Changes
-        env:
-          GH_PAT: ${{ secrets.GH_PAT }}
-        run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add output/
-          git commit -m "Cleanup: Deleted all files inside output directory" || echo "No changes to commit"
-          git push https://x-access-token:${GH_PAT}@github.com/iArchitSharma/thebrief.git HEAD:main
+#       - name: Commit and Push Changes
+#         env:
+#           GH_PAT: ${{ secrets.GH_PAT }}
+#         run: |
+#           git config --global user.name "github-actions[bot]"
+#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
+#           git add output/
+#           git commit -m "Cleanup: Deleted all files inside output directory" || echo "No changes to commit"
+#           git push https://x-access-token:${GH_PAT}@github.com/briefworld/thebrief.git HEAD:main
